src/Zym/Bundle/RouterBundle/Entity/Route.php
<?php

/**
 * Zym Framework
 *
 * This file is part of the Zym package.
 *
 * @link      https://github.com/geoffreytran/zym for the canonical source repository
 * @copyright Copyright (c) 2014 Geoffrey Tran <geoffrey.tran@gmail.com>
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3 License
 */

namespace Zym\Bundle\RouterBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Routing\Route as BaseRoute;
use Symfony\Component\Security\Acl\Model\DomainObjectInterface;

/**
 * Class Route
 *
 * @package Zym\Bundle\RouterBundle\Entity
 * @author  Geoffrey Tran <geoffrey.tran@gmail.com>
 *
 * @ORM\Entity(repositoryClass="Zym\Bundle\RouterBundle\Entity\RouteRepository")
 * @ORM\Table(
 *     name="routes",
 *     indexes={
 *         @ORM\Index(name="weight_idx", columns={"weight"}),
 *     }
 * )
 * @ORM\HasLifecycleCallbacks()
 */
class Route extends BaseRoute implements DomainObjectInterface
{
    /**
     * Name
     *
     * @ORM\Id()
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * Methods
     *
     * @ORM\Column(type="json")
     */
    private $methods = [];

    /**
     * Schemes
     *
     * @ORM\Column(type="json")
     */
    private $schemes = [];

    /**
     * Host
     *
     * @ORM\Column(type="string")
     */
    private $host = '';

    /**
     * Path
     *
     * @ORM\Column(type="string")
     */
    private $path;

    /**
     * Defaults
     *
     * @ORM\Column(type="json")
     */
    private $defaults = [];

    /**
     * Requirements
     *
     * @ORM\Column(type="json")
     */
    private $requirements = [];

    /**
     * Options
     *
     * @ORM\Column(type="json")
     */
    private $options = [];

    /**
     * Weight
     *
     * @var integer
     *
     * @ORM\Column(type="integer")
     */
    private $weight = 0;

    /**
     * UpdatedAt
     *
     * @Gedmo\Timestampable(on="update")
     *
     * @ORM\Column(type="datetime", name="updated_at")
     */
    private $updatedAt;

    /**
     * Compilers
     *
     * @var array
     */
    static protected $compilers = [];

    /**
     * Constructor.
     *
     * Available options:
     *
     *  * compiler_class: A class name able to compile this route instance (RouteCompiler by default)
     *
     * @param string       $name         Name of the route
     * @param string       $path         The path pattern to match
     * @param array        $defaults     An array of default parameter values
     * @param array        $requirements An array of requirements for parameters (regexes)
     * @param array        $options      An array of options
     * @param string       $host         The host pattern to match
     * @param string|array $schemes      A required URI scheme or an array of restricted schemes
     * @param string|array $methods      A required HTTP method or an array of restricted methods
     *
     * @api
     */
    public function __construct($name, $path, array $defaults = [], array $requirements = [], array $options = [], $host = '', $schemes = [], $methods = [])
    {
        $this->setName($name);
        parent::__construct($path, $defaults, $requirements, $options, $host, $schemes, $methods);

        $this->updatedAt = new \DateTime();
    }

    /**
     * Get the name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the name
     *
     * @param string $name
     * @return Route
     */
    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    /**
     * Get the methods
     *
     * @return array
     */
    public function getMethods()
    {
        return $this->methods;
    }

    /**
     * Sets the HTTP methods (e.g. 'POST') this route is restricted to.
     * So an empty array means that any method is allowed.
     *
     * This method implements a fluent interface.
     *
     * @param string|array $methods The method or an array of methods
     *
     * @return Route The current Route instance
     */
    public function setMethods($methods)
    {
        parent::setMethods($methods);
        $this->methods = parent::getMethods();
        return $this;
    }

    /**
     * Returns the lowercased schemes this route is restricted to.
     * So an empty array means that any scheme is allowed.
     *
     * @return array The schemes
     */
    public function getSchemes()
    {
        return $this->schemes;
    }

    /**
     * Sets the schemes (e.g. 'https') this route is restricted to.
     * So an empty array means that any scheme is allowed.
     *
     * This method implements a fluent interface.
     *
     * @param string|array $schemes The scheme or an array of schemes
     *
     * @return Route The current Route instance
     */
    public function setSchemes($schemes)
    {
        parent::setSchemes($schemes);
        $this->schemes = parent::getSchemes();
        return $this;
    }

    /**
     * Returns the pattern for the host.
     *
     * @return string The host pattern
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Sets the pattern for the host.
     *
     * This method implements a fluent interface.
     *
     * @param string $pattern The host pattern
     *
     * @return Route The current Route instance
     */
    public function setHost($pattern)
    {
        parent::setHost($pattern);
        $this->host = parent::getHost();
        return $this;
    }

    /**
     * Get the path
     *
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Set the path
     *
     * @param string $pattern
     * @return Route
     */
    public function setPath($pattern)
    {
        parent::setPath($pattern);
        $this->path = parent::getPath();

        return $this;
    }

    /**
     * Get the defaults
     *
     * @return array
     */
    public function getDefaults()
    {
        return $this->defaults;
    }

    /**
     * Set the defaults
     *
     * @param array $defaults
     * @return Route
     */
    public function setDefaults(array $defaults)
    {
        parent::setDefaults($defaults);
        $this->defaults = parent::getDefaults();
        return $this;
    }

    /**
     * Get the requirements
     *
     * @return array
     */
    public function getRequirements()
    {
        return $this->requirements;
    }

    /**
     * Set the requirements
     *
     * @param array $requirements
     * @return Route
     */
    public function setRequirements(array $requirements)
    {
        parent::setRequirements($requirements);
        $this->requirements = parent::getRequirements();
        return $this;
    }

    /**
     * Get the options
     *
     * @return array
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Set the options
     *
     * @param array $options
     * @return Route
     */
    public function setOptions(array $options)
    {
        parent::setOptions($options);
        $this->options = parent::getOptions();
        return $this;
    }

    /**
     * Get the weight
     *
     * @return integer
     */
    public function getWeight()
    {
        return $this->weight;
    }

    /**
     * Set the weight
     *
     * @param integer $weight
     * @return \Zym\Bundle\RouterBundle\Entity\Route
     */
    public function setWeight($weight)
    {
        $this->weight = $weight;
        return $this;
    }

    /**
     * Get the updated at
     *
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set the updated at time
     *
     * @param \DateTime $updatedAt
     * @return Route
     */
    public function setUpdatedAt(\DateTime $updatedAt)
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }

    /**
     * Refresh the entity
     *
     * @ORM\PostLoad
     */
    public function refreshEntity()
    {
        parent::setPath($this->path);
        parent::setDefaults($this->defaults);
        parent::setRequirements($this->requirements);
        parent::setOptions($this->options);
        parent::setHost($this->host);
        parent::setMethods($this->methods);
        parent::setSchemes($this->schemes);
    }

    /**
     * Returns a unique identifier for this domain object.
     *
     * @return string
     */
    public function getObjectIdentifier()
    {
        return $this->getName();
    }
}

src/Zym/Bundle/RouterBundle/Form/RouteType.php
<?php

/**
 * Zym Framework
 *
 * This file is part of the Zym package.
 *
 * @link      https://github.com/geoffreytran/zym for the canonical source repository
 * @copyright Copyright (c) 2014 Geoffrey Tran <geoffrey.tran@gmail.com>
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3 License
 */

namespace Zym\Bundle\RouterBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;

class RouteType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class)
            ->add('path', TextType::class)
            ->add('defaults', RouteArrayType::class);
            ->add('requirements', RouteArrayType::class, [
                'required' => false,
            ])
            ->add('methods', RouteArrayType::class, [
                'required' => false,
            ])
            ->add('schemes', RouteArrayType::class, [
                'required' => false,
            ])
            ->add('host', TextType::class, [
                'required' => false,
            ])
            ->add('weight', IntegerType::class)
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return '';
    }
}

src/Zym/Bundle/RouterBundle/Controller/RoutesController.php
<?php

/**
 * Zym Framework
 *
 * This file is part of the Zym package.
 *
 * @link      https://github.com/geoffreytran/zym for the canonical source repository
 * @copyright Copyright (c) 2014 Geoffrey Tran <geoffrey.tran@gmail.com>
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3 License
 */

namespace Zym\Bundle\RouterBundle\Controller;

use JMS\SecurityExtraBundle\Annotation\Secure;
use JMS\SecurityExtraBundle\Annotation\SecureParam;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Acl\Domain\ObjectIdentity;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Zym\Bundle\RouterBundle\Entity\Route as RouteEntity;
use Zym\Bundle\RouterBundle\Entity\RouteManager;
use Zym\Bundle\RouterBundle\Form\DeleteType;
use Zym\Bundle\RouterBundle\Form\RouteType;

/**
 * Routes Controller
 *
 * @author    Geoffrey Tran
 * @copyright Copyright (c) 2014 Geoffrey Tran <geoffrey.tran@gmail.com>
 */
class RoutesController extends Controller
{
    /**
     * @Route(
     *     ".{_format}",
     *     name="zym_router_routes",
     *     defaults = { "_format" = "html" }
     * )
     * @Template()
     *
     * @param Request $request
     */
    public function listAction(Request $request)
    {
        $page     = $request->query->get('page', 1);
        $limit    = $request->query->get('limit', 50);
        $orderBy  = $request->query->get('orderBy');
        $filterBy = $request->query->get('filterBy');

        /** @var RouteManager $routeManager */
        $routeManager  = $this->get('zym_router.route_manager');
        $routes        = $routeManager->findRoutes($filterBy, $page, $limit, $orderBy);

        return [
            'routes' => $routes,
        ];
    }

    /**
     * @Route("/add", name="zym_router_routes_add")
     * @Template()
     *
     * @param Request $request
     */
    public function addAction(Request $request)
    {
        $authChecker = $this->get('security.authorization_checker');

        if (!$authChecker->isGranted('CREATE', new ObjectIdentity('class', RouteEntity::class))) {
            throw new AccessDeniedException();
        }

        $route = new RouteEntity(null, null);
        $form = $this->createForm(RouteType::class, $route);

        if ($request->isMethod(Request::METHOD_POST)) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                /** @var RouteManager $routeManager */
                $routeManager = $this->get('zym_router.route_manager');
                $routeManager->createRoute($route);

                return $this->redirectToRoute('zym_router_routes');
            }
        }

        return [
            'form' => $form->createView(),
        ];
    }

    /**
     * Edit a route
     *
     * @param Route $route
     *
     * @Route("/{name}/edit", name="zym_router_routes_edit")
     * @ParamConverter("route", class="ZymRouterBundle:Route")
     * @Template()
     *
     * @SecureParam(name="route", permissions="EDIT")
     */
    public function editAction(Request $request, Route $route)
    {
        $origRoute = clone $route;
        $form = $this->createForm(RouteType::class, $route);

        if ($request->isMethod(Request::METHOD_POST)) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                /** @var RouteManager $routeManager */
                $routeManager = $this->get('zym_router.route_manager');
                $routeManager->saveRoute($route);

                return $this->redirectToRoute('zym_router_routes');
            }
        }

        return [
            'route' => $origRoute,
            'form' => $form->createView(),
        ];
    }

    /**
     * Delete a route
     *
     * @Route(
     *     "/{name}",
     *     requirements={},
     *     methods={"DELETE"}
     * )
     * @Route(
     *     "/{name}/delete.{_format}",
     *     name="zym_router_routes_delete",
     *     defaults={
     *         "_format" = "html"
     *     }
     * )
     *
     * @Template()
     *
     * @SecureParam(name="route", permissions="DELETE")
     *
     * @param Request $request
     * @param Route   $route
     */
    public function deleteAction(Request $request, Route $route)
    {
        $origRoute = clone $route;

        /** @var RouteManager $routeManager */
        $routeManager = $this->get('zym_router.route_manager');
        $form = $this->createForm(DeleteType::class, $route);

        if ($request->isMethod(Request::METHOD_POST)) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $routeManager->deleteRoute($route);

                return $this->redirectToRoute('zym_router_routes');
            }
        }

        if ($request->isMethod(Request::METHOD_DELETE)) {
            $routeManager->deleteRoute($route);

            return $this->redirectToRoute('zym_router_routes');
        }

        return [
            'route' => $origRoute,
            'form' => $form->createView(),
        ];
    }

    /**
     * Show a route
     *
     * @Route(
     *     "/{name}.{_format}",
     *     name     ="zym_router_routes_show",
     *     defaults = { "_format" = "html" }
     * )
     * @ParamConverter("route", class="ZymRouterBundle:Route")
     * @Template()
     *
     * @SecureParam(name="route", permissions="VIEW")
     *
     * @param Route $route
     */
    public function showAction(Route $route)
    {
        return [
            'route' => $route,
        ];
    }
}

src/Zym/Bundle/RouterBundle/Resources/views/Routes/add.html.twig
{% extends "ZymRouterBundle::layout.html.twig" %}

{% block title %}{{ 'Add a Route' | trans({}, 'ZymRouterBundle') }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>
            {{ 'New Route' | trans({}, 'ZymRouterBundle') }}
            <small>{{ 'Create a new route' | trans({}, 'ZymRouterBundle') }}</small>
        </h1>
    </div>

    {{ form_start(form, { 'action': path('zym_router_routes_add'), 'attr': { 'class': 'form-horizontal' } }) }}
        {{ form_rest(form) }}
        <fieldset class="form-actions">
            <button type="submit" class="btn btn-primary">{{ 'Create' | trans({}, 'ZymRouterBundle') }}</button>
            <button type="button" class="btn" onclick="history.back();">{{ 'Cancel' | trans({}, 'ZymRouterBundle') }}</button>
        </fieldset>
    {{ form_end(form) }}
{% endblock %}

src/Zym/Bundle/RouterBundle/Resources/views/Routes/delete.ajax.twig
<div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <h3>{{ 'Confirm Deletion' | trans({}, 'ZymRouterBundle') }}</h3>
</div>

<div class="modal-body">
    <p>
        You are about to delete route <strong>"{{ route.name |e }}"</strong>.
        This action cannot be undone.<br />
        <strong>Are you sure you want to proceed?</strong>
    </p>
</div>

<div class="modal-footer">
    {{ form_start(form, { 'action': path('zym_router_routes_delete', { 'name': route.name }) }) }}
        {{ form_rest(form) }}
        <input class="btn btn-danger" type="submit" value="{{ 'Confirm Deletion' | trans({}, 'ZymRouterBundle') }}" />
        <a href="#" class="btn" data-dismiss="modal">{{ 'Cancel' | trans({}, 'ZymRouterBundle') }}</a>
    {{ form_end(form) }}
</div>

src/Zym/Bundle/RouterBundle/Resources/views/Routes/delete.html.twig
{% extends "ZymRouterBundle::layout.html.twig" %}

{% block title %}{{ 'Delete Route' | trans({}, 'ZymRouterBundle') }}{% endblock %}

{% block content %}
    <h3>{{ 'Confirm Deletion' | trans({}, 'ZymRouterBundle') }}</h3>

    <p>
        You are about to delete route <strong>"{{ route.name |e }}"</strong>.
        This action cannot be undone.<br />
        <strong>Are you sure you want to proceed?</strong>
    </p>

    {{ form_start(form, { 'action': path('zym_router_routes_delete', 'name': route.name) }) }}
        {{ form_rest(form) }}
        <fieldset class="form-actions">
            <button type="submit" class="btn btn-danger">{{ 'Confirm Deletion' | trans({}, 'ZymRouterBundle') }}</button>
            <button type="button" class="btn" onclick="history.back();">{{ 'Cancel' | trans({}, 'ZymRouterBundle') }}</button>
        </fieldset>
    {{ form_end(form) }}
{% endblock %}

src/Zym/Bundle/RouterBundle/Resources/views/Routes/edit.html.twig
{% extends "ZymRouterBundle::layout.html.twig" %}

{% block title %}{{ 'Edit Route' | trans({}, 'ZymRouterBundle') }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>
            {{ 'Edit Route' | trans({}, 'ZymRouterBundle') |e }}
            <small>{{ route.name | trans({}, 'ZymRouterBundle') |e }}</small>
        </h1>
    </div>

    <div class="btn-toolbar">
        <div class="btn-group">
            <a class="btn" href="javascript: history.back();">
                <i class="icon-arrow-left"></i>
                {{ 'Back' | trans({}, 'ZymRouterBundle') }}
            </a>
        </div>

        <div class="btn-group">
            <a class="btn" href="{{ path('zym_security_acl_object_aces', { 'type': 'Zym\\Bundle\\RouterBundle\\Entity\\Route', 'identifier': route.objectIdentifier }) }}">
                <i class="icon-lock"></i>
                {{ 'Permissions' | trans({}, 'ZymRouterBundle') }}
            </a>
        </div>
    </div>

    {{ form_start(form, { 'action': path('zym_router_routes_edit', 'name': route.name), 'attr': { 'class': 'form-horizontal' } }) }}
        {{ form_rest(form) }}
        <fieldset class="form-actions">
            <button type="submit" class="btn btn-primary">{{ 'Save changes' | trans({}, 'ZymRouterBundle') }}</button>
            <button type="button" class="btn" onclick="history.back();">{{ 'Cancel' | trans({}, 'ZymRouterBundle') }}</button>
        </fieldset>
    {{ form_end(form) }}
{% endblock %}

src/Zym/Bundle/RouterBundle/Resources/views/Routes/list.html.twig
{% extends "ZymRouterBundle::layout.html.twig" %}

{% block title %}{{ 'Routes' | trans({}, 'ZymRouterBundle') }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="pull-left">
            {{ 'Routes' | trans({}, 'ZymRouterBundle') }}
            <small>{{ 'Manage routes' | trans({}, 'ZymRouterBundle') }}</small>
        </h1>

        <div class="clearfix" style="clear:both"></div>
    </div>

    <div class="btn-toolbar">
        <div class="btn-group">
            {% if is_granted('CREATE', ['class', 'Zym\\Bundle\\RouterBundle\\Entity\\Route']) %}
            <a class="btn" href="{{ path('zym_router_routes_add') }}">
                <i class="icon-plus"></i>
                {{ 'New Route' | trans({}, 'ZymRouterBundle') }}
            </a>
            {% endif %}
        </div>
    </div>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>{{ 'Name' | trans({}, 'ZymRouterBundle') }}</th>
                <th>{{ 'Path' | trans({}, 'ZymRouterBundle') }}</th>

                <th>{{ 'Actions' | trans({}, 'ZymRouterBundle') }}</th>
            </tr>
        </thead>

        <tbody>
        {% for route in routes %}
            {% if is_granted('VIEW', route) %}
            <tr>
                <td>
                    <a href="{{ path('zym_router_routes_show', { 'name': route.name, '_format': 'html' }) }}">{{ route.name |e }}</a>
                </td>
                <td>
                    {{ route.path |e }}
                </td>
                <td>
                    <div class="btn-group" style="width: 300px">
                        <a class="btn" href="{{ path('zym_router_routes_show', { 'name': route.name, '_format': 'html' }) }}">
                            <i class="icon-share"></i>
                            {{ 'View' | trans({}, 'ZymRouterBundle') }}
                        </a>

                        {% if is_granted('EDIT', route) %}
                        <a class="btn" href="{{ path('zym_router_routes_edit', { 'name': route.name }) }}">
                            <i class="icon-edit"></i>
                            {{ 'Edit' | trans({}, 'ZymRouterBundle') }}
                        </a>
                        {% endif %}

                        {% if is_granted('DELETE', route) %}
                        <a class="btn" href="{{ path('zym_router_routes_delete', { 'name': route.name }) }}" data-toggle="ajax-modal">
                            <i class="icon-remove"></i>
                            {{ 'Delete' | trans({}, 'ZymRouterBundle') }}
                        </a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>

    {% if routes | length <= 0 %}
        <p>
            {{ 'No routes added yet.' | trans({}, 'ZymRouterBundle') }}

            {% if is_granted('CREATE', ['class', 'Zym\\Bundle\\RouterBundle\\Entity\\Route']) %}
            <a class="" href="{{ path('zym_router_routes_add') }}">{{ 'Create a route.' | trans({}, 'ZymRouterBundle') }}</a>
            {% endif %}
        </p>
    {% endif %}

    {{ knp_pagination_render(routes) }}
{% endblock %}

src/Zym/Bundle/RouterBundle/Resources/views/Routes/list.json.twig
{% spaceless %}

{% set menusData = {} %}

{% for menu in menus %}
    {%
        set menusData = menusData | merge({
            "menus": [{
                "id": menu.name,
                "name": menu.label,
                "description": menu.description,
                "options": menu.options
            }]
        })
    %}
{% endfor %}

{{ menusData | json_encode | raw }}
{% endspaceless %}

src/Zym/Bundle/RouterBundle/Resources/views/Routes/show.html.twig
{% extends "ZymRouterBundle::layout.html.twig" %}

{% block title %}{{ 'Viewing Route' | trans({}, 'ZymRouterBundle') }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>
            {{ 'Viewing Route' | trans({}, 'ZymRouterBundle') |e }}
            <small>{{ route.name | trans({}, 'ZymRouterBundle') |e }}</small>
        </h1>
    </div>

    <div class="btn-toolbar">
        <div class="btn-group">
            <a class="btn" href="javascript: history.back();">
                <i class="icon-arrow-left"></i>
                {{ 'Back' | trans({}, 'ZymRouterBundle') }}
            </a>
        </div>

        <div class="btn-group">
            {% if is_granted('EDIT', route) %}
            <a class="btn" href="{{ path('zym_router_routes_edit', { 'name': route.name }) }}">
                <i class="icon-edit"></i>
                {{ 'Edit' | trans({}, 'ZymRouterBundle') }}
            </a>
            {% endif %}

            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <span class="caret"></span>
            </a>

            <ul class="dropdown-menu">
                {% if is_granted('DELETE', route) %}
                <li>
                    <a href="{{ path('zym_router_routes_delete', { 'name': route.name }) }}" data-toggle="ajax-modal">
                        <i class="icon-remove"></i>
                        {{ 'Delete' | trans({}, 'ZymRouterBundle') }}
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>

        <div class="btn-group">
            <a class="btn" href="{{ path('zym_security_acl_object_aces', { 'type': 'Zym\\Bundle\\RouterBundle\\Entity\\Route', 'identifier': route.objectIdentifier }) }}">
                <i class="icon-lock"></i>
                {{ 'Permissions' | trans({}, 'ZymRouterBundle') }}
            </a>
        </div>
    </div>

    <h2>JSON Data</h2>
    <pre>
        {{- route.value | json_encode |e -}}
    </pre>
    
    <h2>Interpreted</h2>
    {% debug route.value %}
{% endblock %}

src/Zym/Bundle/RouterBundle/Resources/views/Routes/show.json.twig
{%
set menuData = {
    "id": menu.id,
    "name": menu.name,
    "label": menu.label,
    "description": menu.description,
    "options": menu.options,
}
%}
{{ menuData | json_encode | raw }}